### PR TITLE
Add extension method for Request telemetry

### PR DESCRIPTION
**Pull request by tomasr**
... to match the corresponding method in the Web SDK.

Also increment the version number and publishing date to resolve build errors.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Hi @tomasr 

Got error in build, can you pls fix it?


F:\A\_work\22\obj\Release\DependencyCallstacks\Net45\AssemblyInfo.g.cs (14, 28)  
 
The specified version string does not conform to the required format - major[.minor[.build[.revision]]]
 


  F:\A\_work\22\obj\Release\DependencyCallstacks\Net45\AssemblyInfo.g.cs (15, 32)  
 
The specified version string does not conform to the recommended format - major.minor.build.revision
 


  F:\A\_work\22\obj\Release\DependencyCallstacks\Net40\AssemblyInfo.g.cs (14, 28)  
 
The specified version string does not conform to the required format - major[.minor[.build[.revision]]]
 


  F:\A\_work\22\obj\Release\DependencyCallstacks\Net40\AssemblyInfo.g.cs (15, 32)  
 
The specified version string does not conform to the recommended format - major.minor.build.revision
 

 
Process 'msbuild.exe' exited with code '1'.

**Comment by tomasr** [comment]
I was getting the same error previously because the SemanticVersionDate in Version.props was too old; I updated it and the error went away. Have you tried doing a Rebuild All?

**Comment by SergeyKanzhelev** [comment]
hm, it is happening on build machine... Maybe `AssemblyInfo.g.cs` not being cleaned up.

@abaranch, @madeleinefletcher - I remember something similar was happening on SDK repository. Do you remember the root cause/remediation?

**Comment by tomasr** [comment]
I see that our Version.props file has this:

```XML
<PreReleaseVersion>$([MSBuild]::Divide($([System.DateTime]::Now.Subtract($([System.DateTime]::Parse($(SemanticVersionDate)))).TotalMinutes), 5).ToString('F0'))</PreReleaseVersion>
```

While you use this for the AI repos:

```XML
    <PreReleaseVersionFilePath>$(MSBuildThisFileDirectory)$(PreReleaseVersionFileName)</PreReleaseVersionFilePath>
```

And dirs.proj has this in the Build step (so possibly it's rewriting the file on each master build with a more sensible version value)
```XML
    <WriteLinesToFile File="$(PreReleaseVersionFileName)" Lines="$(PreReleaseVersion)" Overwrite="true" Encoding="Unicode"/>
```

**Comment by tomasr** [comment]
Looks like the problem is just that the AssemblyInfo.g.cs isn't getting regenerated on each build: 

Skipping target "GenerateAdditionalSources" because all output files are up-to-date with respect to the input files.

Should the build server be doing a Clean;Build rather than just running the Build target?

**Comment by SergeyKanzhelev** [comment]
Oh, I'm sorry for this. I hope you had a backup.

I'll get to it tomorrow and try to fix the build.

**Pull request merged**
